name: Machine Learning CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  mlops-ci:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Ambil seluruh kode repositori ke server runner
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Siapkan lingkungan Python versi 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # 3. Install library MLflow versi terbaru & Pendukung Utamanya
    - name: Install MLflow & Dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy dagshub

    # 4. Login otomatis ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 5. Jalankan MLflow Project (Meneruskan Token DagsHub)
    - name: Run MLflow Project
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd Workflow-CI/MLProject_Folder
        mlflow run . --env-manager=local --experiment-name="CI_Retraining_Pipeline"

    # 6. Mengubah model hasil training menjadi Docker Image
    - name: Build Docker Image using MLflow
      run: |
        cd Workflow-CI/MLProject_Folder
        MODEL_PATH=$(find mlruns/ -type d -name "model" | head -n 1)
        echo "Lokasi model ditemukan di: $MODEL_PATH"
        mlflow models build-docker -m "$MODEL_PATH" -n "${{ secrets.DOCKER_HUB_USERNAME }}/heart-disease-model:latest" --enable-mlserver

    # 7. Kirim Docker Image ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/heart-disease-model:latest